### PR TITLE
Support stack usage measurement

### PR DESCRIPTION
**Pull request by bzsolt**
JSRemoteTest-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by bzsolt** [comment]
The patch is work-in-progress because currently only the rpi2 target supports the stack measure feature.

**Comment by bzsolt** [comment]
@glistening the principle of the stack usage measurement is stack coloration, so the stack area is filled with an uncommon pattern before the program starts, and then count how many pattern remained.
(Stack measurement support for stm32f4 is also added.)

**Comment by yichoi** [comment]
if you done, please remove "[WIP]" prefix.

**Comment by bzsolt** [comment]
@yichoi @glistening 
The PR now covers all supported device.

**Comment by rtakacs** [comment]
LGTM

**Pull request merged**
